server:
  port: 9000
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ece_base
    password: 123456
    url: jdbc:mysql://localhost:3306/ece_base?useSSL=false&serverTimezone=GMT%2B8
    #    druid 线程池配置
    type: com.alibaba.druid.pool.DruidDataSource
    #druid 线程池监控配置

    druid:
      #            监控内容
      aop-patterns: com.show.coreService.*
      #开启监控功能-->指定开启的功能组件  slf4j:开启日志记录/拦截的所有东西都会日志
      filters: stat,slf4j
      filter:
        stat:
          #          慢查询监控
          log-slow-sql: true
          #          慢查询时间
          slow-sql-millis: 1000
          enabled: true

      stat-view-servlet:
        #开启监控功能
        enabled: true
        #设置监控页面访问用户名
        login-username: admin
        #密码
        login-password: 123
        # 监控页面重置按钮是否启用
        reset-enable: false
        #进入监控页面的url --》/druid  就可以
        url-pattern: /druid/*

      web-stat-filter:
        #开启 url监控/关联web-jdbc
        enabled: true
        #拦截所有请求
        url-pattern: /*
        #排除静态资源
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
  # 开启RestFUl风格支持
  mvc:
    hiddenmethod:
      filter:
        enabled: true

    #json 类型数据的数据格式配置
  jackson:
      date-format: yyyy-MM-dd HH-mm-ss
      time-zone: GMT+8


  redis:
    host: localhost
    port: 6379
    password: arvin5181
    database: 0
#    shutdown-timeout: 100000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞时间，负数表示没有限制
        max-idle: 5
        min-idle: 0

#      #客户端配置

#mybatis-plus配置
mybatis-plus:
#  global-config:
#    db-config:
#     logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#     logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#     logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true
    #详细日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: /mapper/**/*.xml

#阿里云  oss配置
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: XXXXXX
      keyid: XXXXXX
      keysecret: XXXXXX
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: XXXXXX
